version: 2.1

jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Dockerfile"
          command: GIT_BRANCH=$CIRCLE_BRANCH ./build.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
        context: dockerhub
