version: 2.1

jobs:
  lint_scripts:
    docker:
      - image: koalaman/shellcheck-alpine:latest
    steps:
      - checkout
      - run:
          name: 'Run Shellcheck'
          command: find . -type f -name '*.sh' | xargs shellcheck -x

  build_image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'Install Dependencies'
          command: 'apk add --no-cache git'
      - run:
          name: 'Build Dockerfile'
          command: |
            # map CircleCI's var to our generic variable
            export GIT_BRANCH="$CIRCLE_BRANCH"

            ./build.sh
workflows:
  version: 2
  lint_then_build:
    jobs:
      - lint_scripts
      - build_image:
          context: dockerhub
          requires:
            - lint_scripts
          filters:
            branches:
              only:
                - master
                - /^release.*/
